[package]
name = "vsdebugeng"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vsdebugeng"
path = "src/vsdebugeng.rs"

[dependencies.windows]
version = "0.38.0"
features = [

]